name: Testing
on:
  pull_request:
    branches:
      - master

jobs:

  migration-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Info migrations
        run: ./gradlew flywayInfo
        env:
          TESTING_DB_URL: ${{ secrets.TESTING_DB_URL }}
          TESTING_DB_USERNAME: ${{ secrets.TESTING_DB_USERNAME }}
          TESTING_DB_PASSWORD: ${{ secrets.TESTING_DB_PASSWORD }}
      - name: Validate migrations
        run: ./gradlew flywayValidate
        env:
          TESTING_DB_URL: ${{ secrets.TESTING_DB_URL }}
          TESTING_DB_USERNAME: ${{ secrets.TESTING_DB_USERNAME }}
          TESTING_DB_PASSWORD: ${{ secrets.TESTING_DB_PASSWORD }}
      - name: Apply migrations
        run: ./gradlew flywayMigrate
        env:
          TESTING_DB_URL: ${{ secrets.TESTING_DB_URL }}
          TESTING_DB_USERNAME: ${{ secrets.TESTING_DB_USERNAME }}
          TESTING_DB_PASSWORD: ${{ secrets.TESTING_DB_PASSWORD }}

  testing:
    runs-on: ubuntu-latest
    needs: migration-testing
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Run tests
        run: ./gradlew check
        env:
          SPRING_PROFILES_ACTIVE: testing